export const PRODUCTS = [
  {
    id: "fan_1",
    name: "Smart Metallic Ceiling Fan",
    description: "High-speed aerodynamic blades with smart remote control.",
    productPrice: 2499,
    installPrice: 299,
    img: "/images/shop_ceiling_fan_1777321934304.png",
    category: "Electrician",
  },
  {
    id: "lock_1",
    name: "Premium Digital Smart Lock",
    description: "Fingerprint, passcode, and app-controlled security lock.",
    productPrice: 6999,
    installPrice: 899,
    img: "/images/shop_smart_lock_1777321948821.png",
    category: "Electrician", 
  },
  {
    id: "tap_1",
    name: "Stainless Steel Kitchen Mixer",
    description: "360-degree rotation, dual-flow premium sink tap.",
    productPrice: 1899,
    installPrice: 399,
    img: "/images/shop_kitchen_tap_1777322007956.png",
    category: "Plumber",
  },
  {
    id: "switch_1",
    name: "Smart Wi-Fi Switchboard",
    description: "App-controlled 4-switch modular board with glass finish.",
    productPrice: 1299,
    installPrice: 249,
    img: "/images/shop_switchboard_1777322019097.png",
    category: "Electrician",
  },
  {
    id: "tv_mount_1",
    name: "Heavy-Duty TV Wall Mount",
    description: "Articulating bracket for 32-65 inch TVs with tilt & swivel.",
    productPrice: 1599,
    installPrice: 499,
    img: "/images/shop_tv_mount_1777325323205.png",
    category: "Electrician",
  },
  {
    id: "water_purifier_1",
    name: "Under-Sink RO Water Purifier",
    description: "7-stage advanced purification system with mineral infuser.",
    productPrice: 12499,
    installPrice: 799,
    img: "/images/shop_water_purifier_1777325370102.png",
    category: "Plumber",
  },
  {
    id: "termite_kit_1",
    name: "Anti-Termite Treatment Kit",
    description: "Professional grade chemical injection kit for woodwork.",
    productPrice: 2199,
    installPrice: 1299,
    img: "/images/shop_termite_kit_1777325380809.png",
    category: "Pest Control",
  }
];
